### ISSUE TITLE
"OpenFace offline.exe" quits when dealing with more than 1700(or so) images.

### ISSUE THREAD

**Issue by CastellanLiu** [TadasBaltrusaitis/OpenFace#488]
When I using OpenFace offline.exe(File->Open image directory) to deal with a directory containing more than 10k images, the program stops and disappears when it processed about 1700 images(I forget the accurate number).
This always shows even if I use another dataset or remove some images, so I'm sure there's nothing wrong with the facial images.

**Comment by TadasBaltrusaitis** [comment]
Thanks for pointing it out, I will investigate further

**Comment by TadasBaltrusaitis** [comment]
Can you try with the latest release now? Should be fixed.

**Comment by CastellanLiu** [comment]
I've just tried the latest version, but the problem seems not solved yet. I tried for serveral times, and found that the problem occurs when dealing with one picture, which is attached here. But I don't know whether there exists ohter images will cause this problem.
![n0015580004](https://user-images.githubusercontent.com/15259250/43352381-30abdcf2-9255-11e8-928e-e61025d4d28a.jpg)

**Comment by CastellanLiu** [comment]
BTW, I just copied the model from ver2.0.2, not downloaded.

**Comment by TadasBaltrusaitis** [comment]
Should be fixed now in the new version (2.0.5), please re-open if it still persists

**Comment by CastellanLiu** [comment]
Yes, thanks and congratulations.
